name: Deploy to Beget

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Deploy to Beget
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.BEGET_FTP_HOST }}
          username: ${{ secrets.BEGET_FTP_USERNAME }}
          password: ${{ secrets.BEGET_FTP_PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: ./build/
          server-dir: /b59170dq.beget.tech/public_html/
          dangerous-clean-slate: true